const dados = [
  { nome: "São Paulo", temp: "25ºC", previsao: "Ensolarado" },
  { nome: "Rio de Janeiro", temp: "28ºC", previsao: "Parcialmente nublado" },
  { nome: "Brasília", temp: "22ºC", previsao: "Céu limpo" },
  { nome: "Salvador", temp: "30ºC", previsao: "Chuvoso" },
  { nome: "Fortaleza", temp: "31ºC", previsao: "Sol e algumas nuvens" },
  { nome: "Belo Horizonte", temp: "23ºC", previsao: "Nublado" },
  { nome: "Manaus", temp: "32ºC", previsao: "Acentuada umidade" },
  { nome: "Recife", temp: "29ºC", previsao: "Chuvoso" },
  { nome: "Porto Alegre", temp: "18ºC", previsao: "Frio e úmido" },
  { nome: "Curitiba", temp: "17ºC", previsao: "Chuvoso" },
  { nome: "Belém", temp: "30ºC", previsao: "Chuvoso" },
  { nome: "Goiânia", temp: "26ºC", previsao: "Ensolarado" },
  { nome: "São Luís", temp: "31ºC", previsao: "Chuvoso" },
  { nome: "Maceió", temp: "28ºC", previsao: "Ensolarado" },
  { nome: "Natal", temp: "30ºC", previsao: "Sol e algumas nuvens" },
  { nome: "João Pessoa", temp: "29ºC", previsao: "Parcialmente nublado" },
  { nome: "Teresina", temp: "32ºC", previsao: "Ensolarado" },
  { nome: "Porto Velho", temp: "33ºC", previsao: "Chuvoso" },
  { nome: "Boa Vista", temp: "31ºC", previsao: "Ensolarado" },
  { nome: "Rio Branco", temp: "30ºC", previsao: "Nublado" },
  { nome: "Campo Grande", temp: "25ºC", previsao: "Céu limpo" },
  { nome: "Cuiabá", temp: "32ºC", previsao: "Muito quente" },
  { nome: "Aracaju", temp: "29ºC", previsao: "Sol e algumas nuvens" },
  { nome: "Vitória", temp: "27ºC", previsao: "Parcialmente nublado" },
  { nome: "Palmas", temp: "30ºC", previsao: "Ensolarado" },
  { nome: "Macapá", temp: "31ºC", previsao: "Chuvoso" },
  { nome: "São Pedro da Aldeia", temp: "26ºC", previsao: "Ensolarado" },
  { nome: "Cabo Frio", temp: "25ºC", previsao: "Parcialmente nublado" },
  { nome: "Angra dos Reis", temp: "27ºC", previsao: "Chuvoso" },
  { nome: "Ilha Grande", temp: "28ºC", previsao: "Ensolarado" },
  { nome: "Búzios", temp: "24ºC", previsao: "Sol e algumas nuvens" },
];

export default dados;
